### ISSUE TITLE
Enhancement requests/suggestions

### ISSUE THREAD

**Issue by AlisterH** [freeshrugsxd/qgis-pathfinder#3]
Hi, I was very pleased to see this plugin - this sort of functionality is very popular for users of GIS, CAD etc.  Personally I have had code in a startup.py creating shortcut keys to provide the same functionality.

Would you consider any of these changes?:
1. Provide an option to copy the path to the containing folder, rather than the full file path.  In my usage probably 95% of the time I only want the folder path.
2. Provide the "copy path" option for all layers, not just file-based layers.  Perhaps you'd need to call it "copy layer source" instead.
3. Show a notification.  It requires very little code and means it is even more useful because (a) the user is more likely to realise sooner if they copied the path of the wrong layer by mistake, and (b) the user can use it if they just want to quickly see the layer source, even if they didn't actually need to copy it.  Something like this is all it takes:
`        iface.messageBar().pushMessage("Layer source copied to clipboard",layerSource, level=Qgis.Success) `

Happy to file these as separate tickets if you want, and look at the code myself if necessary.

**Comment by freeshrugsxd** [comment]
Hey, glad that you like the plugin and thanks for your suggestions!

> Provide an option to copy the path to the containing folder, rather than the full file path.  In my usage probably 95% of the time I only want the folder path.

That's a reasonable request. I was thinking about building a little settings page where one could set stuff like the separator, quoting character and stuff like that. An option to copy the parent folder path instead of file path could also fit in there. Alternatively, there is kind of a "hidden" feature, where an additional entry is shown when shift is pressed, additional entries could go in there, in order to not clutter the context menu too much.

> Provide the "copy path" option for all layers, not just file-based layers. Perhaps you'd need to call it "copy layer source" instead.

This is actually exactly how this plugin used to work at the beginning and I gave it the somewhat clunky name "Copy Source Location". But I never had the situation where I needed the location of a XYZ tile layer or PostGIS table, so I dropped those and went with the whole _path_ theme. What would be your use case here?

> Show a notification. 

I was gonna dismiss this because I think something as basic as "copy to clipboard" does not warrant a notification. I took a great deal of inspiration from the KDE Plasma Desktop environment and you don't get any feedback there either. That being said, your point (b) pretty much sold me on this, I think. I'm still not sure if I want a notification for this or not but having the source/path displayed somewhere just to check would be great!

Thank you very much for these suggestions! 

Your are welcome to send PRs this way, should you have anything implemented.

I will take some time tomorrow and see what I come up with.

Have a nice evening!

**Comment by AlisterH** [comment]
> Alternatively, there is kind of a "hidden" feature, where an additional entry is shown when shift is pressed, additional entries could go in there.

Ah, that is neat, but how is anyone supposed to know about it?

> But I never had the situation where I needed the location of a XYZ tile layer or PostGIS table, so I dropped those and went with the whole path theme. What would be your use case here?

1. Sometimes I make notes in other software outside QGIS about various layers of various different types - at one stage I was doing it enough that I spent the time to put that code in startup.py that I mentioned.  I was tempted to make a plugin for it myself, if I ever found the time.  
Actually, this brings up an important point - even with something like shapefiles a layer may have a source which isn't just the file path, and the user may want either the path, or the full source.  If I set a filter on a shapefile and use the plugin to "Copy Path", it copies the file's path.  This is useful, but if you're doing something like what I just described, you probably want the full source.
I think a settings page would be great, because particularly for file based layers there are a lot of different variations that would be useful in different situations.  You could have checkboxes for a bunch of different options
- \\ substitution like your current hidden feature
- include the filename rather than just the folder
- just output the full source instead of isolating a file path.
- add quotes around the output.  Sometimes these are very helpful, other times they are very unhelpful
- show a notification
Instead of an option to add quotes, if you really wanted to empower users you could allow them to specify one string to prepend to the beginning of the output and another string to append to the end.

2. Sometimes I open a project and I just want to quickly see the source of a layer because I'm not sure where it's from.

> That being said, your point (b) pretty much sold me on this, I think.

Of course, point (b) is less applicable if someone is accessing it with the mouse, because the standard tooltip shows the full layer source.  But people are able to assign a shortcut key and use it like me.  Thinking about it now, I probably use it just as often to simply check what layer is currently selected, without scrolling through the layer list to see.

> I'm still not sure if I want a notification for this or not

If you'd like it displayed _somewhere_ I don't really understand why you wouldn't want it to be a notification.  Notifications are used pretty heavily in QGIS, and it wouldn't be out of place.  There's no reason you couldn't make it optional, especially if you've looking at implementing a settings page anyway.

**Comment by freeshrugsxd** [comment]
Hey,

> Ah, that is neat, but how is anyone supposed to know about it?

Well, there isn't a documentation for anything yet and I also wasn't sure if this feature was there to stay or not.


I don't want to show a notification because I think copying a string to clipboard does not warrant a visual feedback. I want this plugin to be as unintrusive as possible so that it feels like a builtin QGIS feature (because it should be one). See the Copy Cell Content (in the attribute table) or Copy Color actions for example. 
That being said, making it an opt-in feature for people that would like to have a feedback seems reasonable.

I like all your suggestions for possible options and I am already working on it.

My current plans for the settings dialog are:

---
- [x] include file name [default: True]
- [ ] include layer name [default: False]
  - If True:
    - [ ] include filter expressions / sql queries (basically full source) [default: False]
- [ ] copy source location of non-file layer [default: False]
- [ ] add additional backslash [default: False]
- [ ] show a notification [default: False]
- dropdown menu to choose path quoting character [default: none]
- dropdown menu to choose separation character [default: Space]
- type characters to use as prefix/postfix of whole output [default: none]
  - Possibly even allowing pre- and postfix to be different by using two short line edits like: [ " ] _paths_ [ " ] 
---
- [x] use different set of the above options for multi-selections [default: True]
  - defaulting to True to retain the plugins current behavior
  - default change:
    - path quoting character: "
---
- [x] use different set of the above options when Shift is pressed [default: True]
  - defaulting to True to retain the plugins current behavior
  - default change:
    - [ ] add additional backslash
---

Additionally I want to make it possible to assign keybinds to Copy Path and Show in Explorer.
Furthermore, I'm thinking about allowing more modifiers than Shift.

I think implementing all these will take me a few weeks.

Thank you for your feedback and your suggestions!

Greetings

**Comment by AlisterH** [comment]
> Additionally I want to make it possible to assign keybinds to Copy Path and Show in Explorer.

Ideally key bindings would be configurable through "Settings>Keyboard shortcuts"

**Comment by freeshrugsxd** [comment]
Hey,

it has been some time but I bumped the plugin to the next version. I did not implement everything that was discussed in this thread but the hard part is done and stuff like non-file layers support, modifiers or keyboard shortcut assignments will come in a future update. 

Thank you for your feedback!
