### ISSUE TITLE
Plugin has always failed to load with older Python versions (ticket filed for information only)

### ISSUE THREAD

**Issue by AlisterH** [freeshrugsxd/qgis-pathfinder#7]
I'm posting this really for information for anybody else who encounters this problem - if anyone does, I'm afraid they need to upgrade to a QGIS that uses a newer Python version.  Recent versions of QGIS require a newer Python, so they are always OK.
 
I was doing some testing in an environment with QGIS 3.1.0, and found that pathfinder would not load, as it used Python f-strings (introduced in Python 3.6), and this system only has Python 3.5.2.
This is with 0.4.1, which is the last version of the plugin that claimed to support QGIS 3.0.0 as a minimum version.
If someone can't run a QGIS with a new enough Python, they would need to rewrite the plugin, as it looks like it has always used f-strings.
````
Couldn't load plugin 'pathfinder' 

SyntaxError: invalid syntax 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 311, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/alister/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pathfinder/__init__.py", line 24, in 
    from pathfinder.pathfinder import PathfinderPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/alister/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pathfinder/pathfinder.py", line 60
    locale_path = plugin_dir / 'i18n' / f'pathfinder_{locale}.qm'
                                                                ^
SyntaxError: invalid syntax

**Comment by freeshrugsxd** [comment]
Hey @AlisterH thank you for this report.

I make heavy use of f-strings and as you correctly pointed out, they came with Python 3.6. 
I never checked which release of QGIS shipped with that specific version. So the version given in the metadata.txt was just a stupid default. Sorry for the inconvenience. 

In the latest version of pathfinder, I even bumped the minimum required QGIS version to 3.18 (https://github.com/freeshrugsxd/qgis-pathfinder/commit/c657a1539022dcc618627995d2e6efccb48fed8b) because of how pathlibs behaviour changed in Python 3.8. So, I'm keeping track of it now, I just didn't for previous versions.
